{
    login: 'lawrencesnead',
    id: 53885323,
    node_id: 'MDQ6VXNlcjUzODg1MzIz',
    avatar_url: 'https://avatars3.githubusercontent.com/u/53885323?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/lawrencesnead',
    html_url: 'https://github.com/lawrencesnead',
    followers_url: 'https://api.github.com/users/lawrencesnead/followers',
    following_url: 'https://api.github.com/users/lawrencesnead/following{/other_user}',
    gists_url: 'https://api.github.com/users/lawrencesnead/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/lawrencesnead/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/lawrencesnead/subscriptions',
    organizations_url: 'https://api.github.com/users/lawrencesnead/orgs',
    repos_url: 'https://api.github.com/users/lawrencesnead/repos',
    events_url: 'https://api.github.com/users/lawrencesnead/events{/privacy}',
    received_events_url: 'https://api.github.com/users/lawrencesnead/received_events',
    type: 'User',
    site_admin: false,
    name: 'Lawrence Snead',
    company: 'Presidential Bank, FSB',
    blog: 'https://lawrencesnead.github.io/Homework-2/',
    location: 'Ashland, VA',
    email: null,
    hireable: null,
    bio: 'My name is Lawrence Snead. I have always had an interest in coding, and I have joined the University of Richmond Web Development Bootcamp in October of 2019.',
    public_repos: 9,
    public_gists: 0,
    followers: 1,
    following: 1,
    created_at: '2019-08-08T01:43:55Z',
    updated_at: '2020-01-11T23:16:21Z'
  }